force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case Config</label>
    <nameField>
        <label>Case Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>Conf-{000000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AvailableConfigsController.cls
/**
 * @description       : Available configs component apex scontroller
 * @author            : Amol B
 * @last modified on  : 04-29-2023
 * @last modified by  : Amol B
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   04-22-2023   Amol B   Initial Version
**/
public with sharing class AvailableConfigsController {
        
    /**
    * @description Method to fetch all the Configs available
    * @author Amol B | 04-29-2023 
    * @return List<Config__c> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Config__c> getConfigs(){
        try {
            List<Config__c> configList = [SELECT Id, Label__c, Type__c, Amount__c FROM Config__c WITH SECURITY_ENFORCED];
            return configList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description Method to add the selected case configs on the case record.
    * @author Amol B | 04-29-2023 
    * @param configIds 
    * @param caseId 
    * @return String 
    **/
    @AuraEnabled
    public static String addConfigsToCase(List<String> configIds, String caseId){
        String retMsg = ''; 
        String existConfigs = '';
        try {
            List<Config__c> selectedConfigs;
            Map<String, Case_Config__c> configLabelToCCMap = new Map<String, Case_Config__c>();
            for(Case_Config__c cc : [select Id, Label__c, Type__c, Case__c, Case__r.Status FROM Case_Config__c WHERE Case__c = :caseId]){
                if(cc.Case__r.Status.equals('Closed')){
                    return 'Case is closed. Cannot add new configs.';
                }
                if(!configLabelToCCMap.containsKey(cc.Label__c)){
                    configLabelToCCMap.put(cc.Label__c, cc);
                }
            }
            if(!configIds.isEmpty()){
                selectedConfigs = [SELECT Id, Label__c, Type__c, Amount__c FROM Config__c WHERE Id IN :configIds WITH SECURITY_ENFORCED];
            }
            List<Case_Config__c> newCaseConfigs = new List<Case_Config__c>();
            for(Config__c con : selectedConfigs){
                if(!configLabelToCCMap.containsKey(con.Label__c)){
                    newCaseConfigs.add(
                        new Case_Config__c(Label__c = con.Label__c, 
                                           Type__c = con.Type__c,
                                           Amount__c = con.Amount__c,
                                           Case__c = caseId)
                    );
                }else{
                    existConfigs += con.Label__c + ',';
                }
            }
            if(!newCaseConfigs.isEmpty()){
                Database.insert(newCaseConfigs, false);
                retMsg = 'New configs added to case.';                
            }
            retMsg += String.isNotBlank(existConfigs) ? '\nFollowing configs already exist on the case: '+existConfigs.removeEnd(',') : '';
            return retMsg;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}